name: Add changes to Develop Branch

on:
  push:
    branches:
      - main

jobs:
  add-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Verificar si existe la rama 'develop'
        run: |
          if ! git show-ref --quiet refs/heads/develop; then
            echo "La rama 'develop' no existe."
            git checkout -b develop
          else
            echo "La rama 'develop' ya existe. No se realizarán cambios."
            exit 1
          fi

      - name: Agregar cambios a la rama 'develop'
        if: success()
        run: |
          git add .
          git commit -m "Auto commit - Agregar cambios a la rama 'develop'"
          git push origin develop
